# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('users_who_purchased', models.ManyToManyField(related_name='purchased_products', to='login_reg_app.User')),
            ],
        ),
    ]
